apiVersion: v1
data:
  config: |
    FluxNamespace: flux-system
    WegoNamespace: {{.Values.namespace}}
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: weave-gitops-config
  namespace: { { .Values.namespace } }
