apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apps.wego.weave.works
spec:
  group: wego.weave.works
  scope: Cluster
  names:
    kind: Application
    listKind: ApplicationList
    plural: apps
    singular: app
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["url", "path"]
          properties:
            url:
              type: "string"
              minimum: 1
              maximum: 1
            path:
              type: "string"
              minimum: 1
              maximum: 1
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
---
