{{- if .Values.adminUser.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.adminUser.username }}-user-read-resources
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: User
    name: wego-admin
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: wego-admin-role
  apiGroup: rbac.authorization.k8s.io
{{- if ne .Release.Namespace "flux-system" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wego-test-user-read-resources
  namespace: flux-system
subjects:
  - kind: User
    name: {{ .Values.adminUser.username }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: wego-admin-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
{{- if .Values.adminUser.createClusterRole }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.adminUser.username }}-user-read-resources-cr
subjects:
- kind: User
  name: {{ .Values.adminUser.username }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: wego-admin-cluster-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
