{{- if .Values.oidcSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: oidc-auth
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  {{- with .Values.oidcSecret }}
  clientID: {{ .clientID | required "oidcSecret.clientID must be set" | b64enc | quote }}
  clientSecret: {{ .clientSecret | required "oidcSecret.clientSecret must be set" | b64enc | quote }}
  issuerURL: {{ .issuerURL | required "oidcSecret.issuerURL must be set" | b64enc | quote }}
  redirectURL: {{ .redirectURL | required "oidcSecret.redirectURL must be set" | b64enc | quote }}
  {{- end }}
{{- end }}
