
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: apps.wego.weave.works
spec:
  group: wego.weave.works
  names:
    kind: Application
    listKind: ApplicationList
    plural: apps
    singular: app
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Application is the Schema for the applications API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ApplicationSpec defines the desired state of Application
            properties:
              branch:
                description: Branch is the branch in the repository where the k8s
                  yaml files for this application are stored.
                type: string
              config_url:
                description: ConfigURL is the address of the git repository containing
                  the automation for this application
                type: string
              deployment_type:
                description: DeploymentType is the deployment method used to apply
                  the manifests
                enum:
                - helm
                - kustomize
                type: string
              helm_target_namespace:
                description: HelmTargetNamespace is the namespace in which to deploy
                  an added Helm Chart
                type: string
              path:
                description: Path is the path in the repository where the k8s yaml
                  files for this application are stored.
                type: string
              source_type:
                description: SourceType is the type of repository containing the app
                  manifests
                enum:
                - helm
                - git
                type: string
              url:
                description: URL is the address of the git repository for this application
                type: string
            type: object
          status:
            description: ApplicationStatus defines the observed state of Application
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
