[flux]
version="0.24.1"
tarpath="https://github.com/fluxcd/flux2/releases/download/v${version}/flux_${version}_${goos}_${goarch}.tar.gz"
txtpath="https://github.com/fluxcd/flux2/releases/download/v${version}/flux_${version}_checksums.txt"
bindir="../pkg/flux/bin"

[envtest]
version="1.19.2"
special_tarpath="https://storage.googleapis.com/kubebuilder-tools/kubebuilder-tools-${version}-${goos}-${goarch}.tar.gz;kubebuilder/bin"
