---
image:
  tag: latest
  pullPolicy: Always
  repository: localhost:5001/weaveworks/wego-app

logLevel: debug

rbac:
  viewSecretsResourceNames: ["cluster-user-auth", "oidc-auth"]

adminUser:
  create: true
  username: dev
  # 'dev'
  passwordHash: $2y$10$pcy9FV0WMQZUHFDcud8JuecIxlUS/Eh9X.iitZtJEYYHUhKyzlJYm

metrics:
  enabled: true

envVars:
  - name: WEAVE_GITOPS_FEATURE_TENANCY
    value: "true"
  - name: WEAVE_GITOPS_FEATURE_CLUSTER
    value: "false"
  - name: WEAVE_GITOPS_FEATURE_TELEMETRY
    value: "true"
  - name: WEAVE_GITOPS_FEATURE_DEV_MODE
    value: "true"
