---
image:
  tag: latest
  pullPolicy: Always
  repository: localhost:5001/weaveworks/wego-app

logLevel: debug

rbac:
  viewSecretsResourceNames: ["cluster-user-auth", "oidc-auth"]

adminUser:
  create: true
  username: dev
  # 'dev'
  passwordHash: $2y$10$pcy9FV0WMQZUHFDcud8JuecIxlUS/Eh9X.iitZtJEYYHUhKyzlJYm

metrics:
  enabled: true

envVars:
  - name: WEAVE_GITOPS_FEATURE_TENANCY
    value: "true"
  - name: WEAVE_GITOPS_FEATURE_CLUSTER
    value: "false"
  - name: WEAVE_GITOPS_FEATURE_TELEMETRY
    value: "false"
  - name: WEAVE_GITOPS_FEATURE_OIDC_BUTTON_LABEL
    value: "Login with SSO"
  - name: WEAVE_GITOPS_FEATURE_DEV_MODE
    value: "true"


# Run the UI and API under /wego
additionalArgs:
  - "--route-prefix=/wego"

# Enable ingress running under a path
# Note:
# Run ./tools/kind-with-ingress.sh # create a kind cluster with ingress
# Open http://localhost:30080/wego # access the wego app
# ingress:
#   enabled: true
#   hosts:
#   - host: ""
#     paths:
#       - path: /wego
#         pathType: Prefix