name: Build and Push image

on:
  workflow_call:
    inputs:
      file:
        required: true
        type: string
      flavor:
        type: string
      image:
        required: true
        type: string
      platforms:
        type: string
      push:
        required: true
        type: boolean
      ref:
        type: string
      tags:
        required: true
        type: string

permissions:
  contents: read # for actions/checkout to fetch code

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write # for docker/build-push-action to push images
      id-token: write # for Cosign to be able to sign images with GHA token
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.ref }}
      - name: Unshallow
        if: ${{ inputs.ref != '' }}
        run: |
          git fetch --prune --unshallow
          git fetch --tags -f
      - name: Set build-time flags
        run: |
          echo "LDFLAGS=$(make echo-ldflags)" >> $GITHUB_ENV
          echo "FLUX_VERSION=$(make echo-flux-version)" >> $GITHUB_ENV
      - uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        id: meta
        with:
          images: ${{ inputs.image }}
          tags: ${{ inputs.tags }}
          flavor: ${{ inputs.flavor }}
      - name: setup qemu
        if: ${{ inputs.platforms != '' }}
        uses: docker/setup-qemu-action@53851d14592bedcffcf25ea515637cff71ef929a # v3.3.0
      - uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0
      - uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@b32b51a8eda65d6793cd0494a773d4f6bcef32dc # v6.11.0
        id: build
        with:
          context: .
          platforms: ${{ inputs.platforms }}
          file: ${{ inputs.file }}
          build-args: |
            FLUX_VERSION=${{ env.FLUX_VERSION }}
            LDFLAGS=${{ env.LDFLAGS }}
            GIT_COMMIT=${{ github.sha }}
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Install cosign
        if: ${{ inputs.push }}
        uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da # v3.7.0
      - name: Keyless signing of image
        if: ${{ inputs.push }}
        run: |
          echo ${{ steps.build.outputs.metadata }} | jq .
          cosign sign --yes ${{ inputs.image }}@${{ steps.build.outputs.digest }}
      - name: Verify the image signing
        if: ${{ inputs.push }}
        run: |
          cosign verify ${{ inputs.image }}@${{ steps.build.outputs.digest }} \
            --certificate-identity "https://github.com/${{ github.workflow_ref }}" \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" | jq .
