on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches:
      - main
name: label
jobs:
  labelCheck:
    name: Check that PR has a label for use in release notes
    runs-on: ubuntu-latest
    steps:
      - name: Pull request label check
        uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 1
          labels: "bug, enhancement, ui, test, exclude from release notes"
